name: Latest Blog Posts

on:
  schedule:
    - cron: "30 19 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Update latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://justloseit.top/atom.xml"
          disable_item_validation: true
          item_exec: "if (!post.title) post = null;"
          date_format: yy-mm-dd
